version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "%(asctime)s - %(levelname)s - %(message)s"
            datefmt: '%Y/%m/%d %H:%M:%S'
handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: ../logs/info.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: ../logs/errors.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
loggers:
    info:
            level: INFO
            handlers: [console,info_file_handler,error_file_handler]
            propagate: no
    error:
            level: ERROR
            handlers: [error_file_handler]
            propagate: no
root:
    level: INFO
    handlers: [console,info_file_handler,error_file_handler]